└──Funcs
    └──FuncDecl
        ├──ID: sumThree
        ├──Type: int
        ├──Formals
        │   ├──Formal
        │   │   ├──ID: a
        │   │   └──Type: int
        │   ├──Formal
        │   │   ├──ID: b
        │   │   └──Type: int
        │   └──Formal
        │       ├──ID: c
        │       └──Type: int
        └──Statements
            └──Return
                └──BinOp: +
                    ├──BinOp: +
                    │   ├──ID: a
                    │   └──ID: b
                    └──ID: c
